version: '3.1'
services:
  mysql:
    image: mysql:8.0.17
    restart: always
    container_name: mysql
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - /home/apps/mysql/config:/etc/mysql/conf.d
      - /home/apps/mysql/data:/var/lib/mysql
  
